apiVersion: v1
kind: Service
metadata:
  name: angular-chat-app-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app: angular-chat-app-deployment
