apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: LoadBalancer
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
    - name: external
      port: 9093
      targetPort: 9093
  selector:
    app: kafka-node