apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.9
        ports:
            - containerPort: 2181
        env:
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "ruok,stat,mntr,conf"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports: 
    - port: 2181
  selector:
    app: zookeeper
  
